### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by infinitepower18** [schlopp96/V2Mp3#11] opened 2022-07-10 11:04 UTC
I installed it successfully with pip install but it fails to run.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/44692189/178142196-87970394-4a90-43eb-939a-42d0ac7a7a90.png">

I'm using an Apple Silicon Mac if it helps.

**Comment by schlopp96** [comment] 2022-07-22 23:46
> I installed it successfully with pip install but it fails to run.
> 
> <img alt="image" width="682" src="https://user-images.githubusercontent.com/44692189/178142196-87970394-4a90-43eb-939a-42d0ac7a7a90.png">
> 
> I'm using an Apple Silicon Mac if it helps.

@infinitepower18  Oh crap!! 

I never specified anywhere that currently **V2Mp3** only works with Windows at the moment, did I...

That's absolutely 100% my fault, and I apologize... The next update (or maybe sooner than that once committed to the `dev` branch) will have MacOS functionality!

Also just wanted to say that you're my first ever "Issue" poster on _any_ of my repositories, so thank you very much for giving a small-time developer some much needed motivation and lowering my imposter-syndrome just a tad!! 

Your issue will _quite literally_ have my full attention until it is fixed!!

Thank you again for bringing this to my attention and I'll be sure to let you know the second I fix the issue!

**Comment by schlopp96** [comment] 2022-07-27 20:21
@infinitepower18 Ok I _THINK_ I figured out the issue.

## My findings:

So I found that when installing **V2Mp3** through pip using MacOS, the primary entry point file `"main.pyw"` is **NOT** included in the package. I would assume it has something to do with the "`*.pyw`" file extension, as on Windows, "`main.pyw`" appears to be included in the package download. 

However, even if `"main.pyw"` IS downloaded, **neither MacOS nor Linux can run "*.pyw" file types**, as discussed [here](https://stackoverflow.com/questions/45976196/how-to-open-pyw-files-on-macos#:~:text=PYW%20files%20only%20work%20in,in%20Mac%20and%20Linux%20systems.).

This I did not know, so I certainly learned something new haha...

## The Fix
1. Download _**V2Mp3-v0.2.0**_ from [this page](https://github.com/schlopp96/V2Mp3/releases/tag/v0.2.0).
2. Rename `"./V2Mp3/main.pyw"` to `"./V2Mp3/main.py"`. 

- You (hopefully) should not have any issues from that point forward.

- Versions/dev-branch commits >0.2.0 no longer include the "*.pyw" extension, so this should NOT be an issue going forward.

---

Give this a try and let me know what happens. If this doesn't solve the issue, or something else isn't working as intended, please let me know!

Again, thank you @infinitepower18 for bringing this issue to my attention - have a great day!

**Comment by infinitepower18** [comment] 2022-07-27 20:32
This worked, but now I get an error related to the ffmpeg exe not being found, and obviously exe files won't run on macOS or Linux.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/44692189/181366642-1af2bfb7-226a-47b4-a014-cfdc35faee9f.png">

**Comment by schlopp96** [comment] 2022-07-27 20:52
This is really odd, as it seemed to work fine on my Mac.... did you try installing all dependencies using `pip install -r "requirements.txt"`?

It seems that you might also need a version of `ffmpeg` installed on your system... There is a working Mac installation of it on [this page](https://ffmpeg.org/download.html#build-mac).

**Comment by infinitepower18** [comment] 2022-07-27 20:54
It installed the required dependencies when I installed the wheel package... by any chance are you using an Intel Mac? I checked the ffmpeg website and there is no build for Apple Silicon available nor does the developer have any interest to provide a build.

**Comment by schlopp96** [comment] 2022-07-27 21:15
Ohhh that could be the issue... I borrowed a family member's mac to give it a try, which after just now trying again it seemed to work just fine. But after checking it is indeed an Intel Mac.... Damn dude I'm so sorry for making you try all these things only for it to not work at all in the end...

I may need to try using different dependencies that don't rely on `ffmpeg` for file conversion in that case...

If it wasn't already obvious before, I'm quite unfamiliar with Mac as you can tell...

**Comment by infinitepower18** [comment] 2022-07-27 21:47
It's alright, I guess we are still going through the Apple Silicon transition period lol. I have used Intel Macs before (including an old MBP I got as a hands me down years ago which I used for a brief period before it broke down) but only started using Apple Silicon a month ago. So far things are smooth it's just these minor issues which I will just use my Windows laptop for if needed.

UPDATE: There seem to be some ways available to get ffmpeg on Apple Silicon, will try when I have time.

**Comment by schlopp96** [comment] 2022-07-28 00:21
> It's alright, I guess we are still going through the Apple Silicon transition period lol. I have used Intel Macs before (including an old MBP I got as a hands me down years ago which I used for a brief period before it broke down) but only started using Apple Silicon a month ago. So far things are smooth it's just these minor issues which I will just use my Windows laptop for if needed.
> 
> UPDATE: There seem to be some ways available to get ffmpeg on Apple Silicon, will try when I have time.

Excellent! I'll be sure to check here often.

**Comment by infinitepower18** [comment] 2022-07-28 14:13
I managed to get it working! The problem is the imageio-ffmpeg package not having a Mac ARM64 wheel. To fix this you download the Intel wheel from the PyPi website, change the .whl extension to .zip, unzip the file and copy the contents to the site-packages folder of your Python installation.

Once that's done the program works perfectly.

**Comment by schlopp96** [comment] 2022-07-30 00:21
> I managed to get it working! The problem is the imageio-ffmpeg package not having a Mac ARM64 wheel. To fix this you download the Intel wheel from the PyPi website, change the .whl extension to .zip, unzip the file and copy the contents to the site-packages folder of your Python installation.
> 
> Once that's done the program works perfectly.

Excellent!! I can't express to you _just_ how happy this makes me to hear! Seriously, I _greatly_ appreciate you taking the time to help me figure out a solution to this issue! The easier it is for others to utilize/access my amateurish software, the better...!

Maybe there's a way I could integrate this fix into the PyPI package to ensure compatibility with MacOS right off the bat?

Looks like I have some more work to do 😅

Seriously, @infinitepower18, thank you so very much for your feedback and help!! If there's anything else I can help with, or if any other issues arise, please let me know!!!

Have a good weekend!

**Closed as completed** 2022-07-30 00:22 UTC
Labels: bug, enhancement, important

**Comment by infinitepower18** [comment] 2022-07-30 07:23
I had tried making a macOS app from it using py2app, and while I did manage to get it to run, for some reason it crashes if you run it on a system without Python installed, which is not supposed to be the case. So that's something that needs to be figured out. You also have to create one for Apple Silicon and one for Intel, one universal app won't work.

For Windows you can use Nuitka, just run the command `nuitka --standalone main.py --enable-plugin=tk-inter --windows-disable-console`. I haven't tried this but I use Nuitka for my app and this command works for me. Also if you see any red text saying to enable plugins during the compilation process, cancel it and add the plugins in your command.
